# Generated by Django 2.0.7 on 2020-02-27 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('sript_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Analytic',
            },
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('State', models.CharField(default='Running', max_length=50)),
                ('SubmittedBy', models.CharField(default=' ', max_length=50)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Hostname', models.CharField(max_length=50)),
                ('Result', models.CharField(max_length=250)),
                ('JobState', models.CharField(default='Running', max_length=50)),
            ],
            options={
                'verbose_name': 'Report',
            },
        ),
        migrations.CreateModel(
            name='patch_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('host_name', models.CharField(default=' ', max_length=100)),
                ('State', models.CharField(default=' ', max_length=50)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('pre_cves_important', models.CharField(default=' ', max_length=100)),
                ('pre_cves_critical', models.CharField(default=' ', max_length=100)),
                ('post_cves_critical', models.CharField(default=' ', max_length=100)),
                ('owner_email', models.CharField(default=' ', max_length=100)),
                ('pre_cves_low', models.CharField(default=' ', max_length=100)),
                ('pre_kernel', models.CharField(default=' ', max_length=100)),
                ('pre_os_version', models.CharField(default=' ', max_length=100)),
                ('cves_pending', models.CharField(default=' ', max_length=100)),
                ('cves_status', models.CharField(default=' ', max_length=100)),
                ('snapshot_date', models.CharField(default=' ', max_length=100)),
                ('uptrack_status', models.CharField(default=' ', max_length=100)),
                ('upgraded_kernel', models.CharField(default=' ', max_length=100)),
                ('pre_cves_moderate', models.CharField(default=' ', max_length=100)),
                ('date_patched', models.CharField(default=' ', max_length=100)),
                ('non_uek_status', models.CharField(default=' ', max_length=100)),
                ('kernel_status', models.CharField(default=' ', max_length=100)),
                ('reboot_status', models.CharField(default=' ', max_length=100)),
                ('post_cves_moderate', models.CharField(default=' ', max_length=100)),
                ('updated_os_version', models.CharField(default=' ', max_length=100)),
                ('post_cves_important', models.CharField(default=' ', max_length=100)),
                ('post_cves_low', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'verbose_name': 'CpuPatchData',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Owner', models.CharField(default=' ', max_length=50)),
                ('WF', models.CharField(blank=True, max_length=50)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('HostCount', models.IntegerField(blank=True)),
                ('State', models.CharField(default=' ', max_length=50)),
                ('JobState', models.CharField(default='Running', max_length=50)),
                ('running_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('NonSuccess_count', models.IntegerField(default=0)),
                ('InValidHosts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ScheduledJob',
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(blank=True, max_length=50)),
                ('script', models.CharField(blank=True, max_length=500)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Scripts',
            },
        ),
    ]
