# Generated by Django 2.0.7 on 2020-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='script_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
