# Generated by Django 2.0.7 on 2020-02-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0002_auto_20200227_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='script',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
