# Generated by Django 2.0.7 on 2020-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0003_auto_20200227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='sript_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='Result',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scheduledjobs',
            name='WF',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
