- hosts: "{{ oc_hosts }}"
  remote_user:  "{{ oci_user }}"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false

  tasks:
  - name: Setting BO
    shell: su - emdadm -c 'emctl start blackout "Oct_CPU_Patch2021"  -nodeLevel -d 600 -nowait'
    register: output


  - debug:
       msg: "{{ output.stdout }}"

