- hosts: all
  remote_user: srgadi
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false

  tasks:
  - name: uptime
    shell: uptime
    register: output


  - debug:
       msg: "{{ output.stdout }}"

