- hosts: all
  strategy: free
  gather_facts: false
#  serial: 200
#
  tasks:
  - name: copy universal script
    copy:
      dest: /tmp/universal_patch.py
      src: /scratch/oit-ansi/scripts/universal_patch.py

  - name: remove old dtrace
    shell: "uname -r | grep ^3.8.13 > /dev/null; if [ $? -eq 0 ]; then yum --disablerepo='*' remove dtrace-modules-3.8.13-68.3.4.el6uek-0.4.3-4.el6.x86_64  dtrace-modules-3.8.13-118.13.3.el6uek-0.4.5-3.el6.x86_64 dtrace-modules-3.8.13-44.1.1.el6uek-0.4.3-4.el6.x86_64 dtrace-modules-3.8.13-118.20.2.el6uek-0.4.5-3.el6.x86_64 -y; else "HOST is NOT RUNNING WITH UEK3";fi"
    register: output

  - debug:
     var: output.stdout_lines
      

  - name: Executing job
    shell: nohup python /tmp/universal_patch.py &
    register: output
    ignore_errors: yes

  - name: Get status
    set_fact:
      job_status: "{{ 'OK' if output.rc == 0  else 'FAIL' }}"

  - debug:
       msg: "{{ inventory_hostname }} : {{ job_status }}"


