- hosts: all
  strategy: free
  gather_facts: false
#  serial: 200
#
  tasks:
  - name: copy universal script
    copy:
      dest: /tmp/universal_patch_touek4.py
      src: /scratch/oit-ansi/scripts/universal_patch_touek4.py

  - name: Executing job
    shell: "unset http_proxy https_proxy ;nohup python /tmp/universal_patch_touek4.py &"
    register: output
    ignore_errors: yes

  - name: Get status
    set_fact:
      job_status: "{{ 'OK' if output.rc == 0  else 'FAIL' }}"

  - debug:
       msg: "{{ inventory_hostname }} : {{ job_status }}"


