- hosts: all
  gather_facts: false

  tasks:
  - name: copying script
    copy:
      dest: /tmp/monthly_patch_validate.py
      src: /scratch/srgadi/script/monthly_patch_validate.py


  - name: Getting logs
    shell: python /tmp/monthly_patch_validate.py
    register: output

  - debug:
     msg : "{{ output.stdout }}"

#  - name: Updating log file
#    file:
#        path: "/tmp/oit_patch_validate_{{cr_num}}_{{ lookup('pipe', 'date +%Y%M%d%H%M%S') }}.log"
#        state: touch
#        owner: root
#        group: sys
#        mode: 0555
#    run_once: true
#    register: local_log_file
#    delegate_to: localhost
#
#  #- name: get hostname
#  #  shell: hostname -s
#  #  register: hst
#
#  - name: facts
#    set_fact:
#       #complt_data : "{{ hst.stdout + ':' + output.stdout_lines[-1] }}"
#       complt_data : "{{ output.stdout_lines[-1] }}"
#
#
#  - debug:
#     msg: "Log file : {{ local_log_file.dest }}"
#
#
#  - local_action: lineinfile line={{ complt_data }} path={{ local_log_file.dest }}
#
#  - debug:
#     msg: "{{ output.stdout_lines[-1] }}"
